### ISSUE TITLE
Issue in Integration of Wallet

### ISSUE THREAD

**Issue by asilenced** [asilenced/eth-nextjs-boilerplate#1]
Hello. 
I integrated "connect wallet" button, but it doesn't work now. Please help me.

**Comment by 486xtm** [comment]
import "./App.css";
import { TonConnectButton } from "@tonconnect/ui-react";
import { useCounterContract } from "./hooks/useCounterContract";
import { useTonConnect } from "./hooks/useTonConnect";
function App() {
  const { connected } = useTonConnect();
  const { value, address, sendIncrement } = useCounterContract();
  return (
    <>
      <div className="Container">
        <TonConnectButton />
        <div className="Card">
          <b>Counter Address</b>
          <div className="Hint">{address?.slice(0.3) + "..."}</div>
        </div>
        <div className="Card">
          <b>Counter Value</b>
          <div>{value ?? "Loading"}</div>
        </div>
        <a
          className={`Button ${connected ? 'Active' : 'Disabled'}`}
          onClick={() => {
            sendIncrement();
          }}
        >
          Increment
        </a>
      </div>
    </>
  );
}

export default App;
This is a wallet connect code of Ton Chain.

**Comment by asilenced** [comment]
> import "./App.css"; import { TonConnectButton } from "@tonconnect/ui-react"; import { useCounterContract } from "./hooks/useCounterContract"; import { useTonConnect } from "./hooks/useTonConnect"; function App() { const { connected } = useTonConnect(); const { value, address, sendIncrement } = useCounterContract(); return ( <>
> 
> 
> 
> 
> Counter Address
> {address?.slice(0.3) + "..."}
> 
> 
> 
> Counter Value
> {value ?? "Loading"}
> 
> 
> <a
> className={`Button ${connected ? 'Active' : 'Disabled'}`}
> onClick={() => {
> sendIncrement();
> }}
> >
> Increment
> 
> 
> </>
> );
> }
> export default App; This is a wallet connect code of Ton Chain.

Thank you @486xtm, how can i use this component?

**Comment by 486xtm** [comment]
> > import "./App.css"; import { TonConnectButton } from "@tonconnect/ui-react"; import { useCounterContract } from "./hooks/useCounterContract"; import { useTonConnect } from "./hooks/useTonConnect"; function App() { const { connected } = useTonConnect(); const { value, address, sendIncrement } = useCounterContract(); return ( <>
> > Counter Address
> > {address?.slice(0.3) + "..."}
> > Counter Value
> > {value ?? "Loading"}
> > <a
> > className={`Button ${connected ? 'Active' : 'Disabled'}`}
> > onClick={() => {
> > sendIncrement();
> > }}
> > > 
> > 
> > 
> > Increment
> > </>
> > );
> > }
> > export default App; This is a wallet connect code of Ton Chain.
> 
> Thank you @486xtm, how can i use this component?

To use this code you have to install TonChain Wallet such as Tonkeeper Wallet and scan QR code with your phone.

**Comment by asilenced** [comment]
> > > import "./App.css"; import { TonConnectButton } from "@tonconnect/ui-react"; import { useCounterContract } from "./hooks/useCounterContract"; import { useTonConnect } from "./hooks/useTonConnect"; function App() { const { connected } = useTonConnect(); const { value, address, sendIncrement } = useCounterContract(); return ( <>
> > > Counter Address
> > > {address?.slice(0.3) + "..."}
> > > Counter Value
> > > {value ?? "Loading"}
> > > <a
> > > className={`Button ${connected ? 'Active' : 'Disabled'}`}
> > > onClick={() => {
> > > sendIncrement();
> > > }}
> > > > 
> > > 
> > > 
> > > Increment
> > > </>
> > > );
> > > }
> > > export default App; This is a wallet connect code of Ton Chain.
> > 
> > 
> > Thank you @486xtm, how can i use this component?
> 
> To use this code you have to install TonChain Wallet such as Tonkeeper Wallet and scan QR code with your phone.

Thank you very much for your help. I fix the issues. Thanks again.
